org.gradle.jvmargs=-Xmx3G
mod_name=ProjectEX
mod_id=projectex
mod_description=Unofficial continuation of FTB-ProjectEX [WIP]
package_group=com.latmod.mods
mod_version=1.3.0-alpha
mod_reference=ProjectEX.java
mc_version=1.12.2
curseforge_id=311378
forge_version=14.23.5.2860
mappings_channel=stable
mappings_version=39-1.12
projecte_file=2702991
jei_file=5846804